#!/usr/bin/env python3

"""
Rishu Python Reporting System (Pro Level)
Runs on Termux / Linux
Generates Professional PDF Reports
"""

import os
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

# -------------------------------
# CONFIG
# -------------------------------
OUTPUT_FILE = "Rishu_python_reporting.pdf"

# -------------------------------
# SAMPLE DATA (You can replace)
# -------------------------------
def get_data():
    data = [
        ["Name", "Marks", "Status"],
        ["Rishu", 85, "Pass"],
        ["Aman", 72, "Pass"],
        ["Rahul", 40, "Fail"],
        ["Sita", 91, "Pass"],
    ]
    return data

# -------------------------------
# PDF GENERATOR
# -------------------------------
def generate_pdf(data):
    doc = SimpleDocTemplate(OUTPUT_FILE)
    styles = getSampleStyleSheet()

    elements = []

    # Title
    elements.append(Paragraph("Rishu Python Reporting System", styles['Title']))
    elements.append(Spacer(1, 10))

    # Date
    date = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
    elements.append(Paragraph(f"Generated on: {date}", styles['Normal']))
    elements.append(Spacer(1, 20))

    # Table
    table = Table(data)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
    ]))

    elements.append(table)

    # Footer
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("Generated by Rishu Reporting System", styles['Italic']))

    doc.build(elements)

# -------------------------------
# MAIN FUNCTION
# -------------------------------
def main():
    print("Starting Reporting System...")
    data = get_data()
    generate_pdf(data)
    print(f"Report Generated Successfully: {OUTPUT_FILE}")

# -------------------------------
# RUN
# -------------------------------
if __name__ == "__main__":
    main()
